# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-12 08:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=32, unique=True, verbose_name='key')),
                ('title', models.CharField(max_length=60, verbose_name='\u6807\u9898')),
                ('summary', models.CharField(max_length=200, verbose_name='\u6458\u8981')),
                ('photo', models.ImageField(upload_to=b'', verbose_name='\u56fe\u7247')),
                ('img_url', models.CharField(max_length=100, verbose_name='\u56fe\u7247\u5730\u5740')),
                ('category', models.CharField(choices=[('read', '\u8bfb\u4e66'), ('code', '\u7f16\u7a0b'), ('invest', '\u6295\u8d44'), ('note', '\u7b14\u8bb0')], max_length=20, verbose_name='\u5206\u7c7b')),
                ('content', models.TextField(verbose_name='\u5185\u5bb9')),
                ('status', models.SmallIntegerField(choices=[(0, '\u8349\u7a3f'), (1, '\u6b63\u5e38')], default=0, verbose_name='\u72b6\u6001')),
                ('slug', models.SlugField(max_length=60, verbose_name='\u8f6c\u4e49key')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65e5\u671f')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='\u66f4\u65b0\u65e5\u671f')),
                ('is_top', models.BooleanField(default=False, verbose_name='\u7f6e\u9876')),
                ('view_times', models.IntegerField(default=0, verbose_name='\u6d4f\u89c8\u6b21\u6570')),
                ('zan_times', models.IntegerField(default=0, verbose_name='\u8d5e\u6b21\u6570')),
                ('is_removed', models.BooleanField(default=False, verbose_name='\u662f\u5426\u5220\u9664')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u4f5c\u8005')),
            ],
            options={
                'ordering': ['-is_top', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=32, unique=True, verbose_name='key')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='\u540d\u79f0')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(max_length=60, verbose_name='\u8f6c\u4e49key')),
                ('is_removed', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.Tag', verbose_name='\u6807\u7b7e'),
        ),
    ]
